name: Docker test
on: [ workflow_call ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env context
        run: |
          echo RUN_STAMP=docker-${{ runner.os }}-${{ inputs.name }} >>$GITHUB_ENV

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.RUN_STAMP }}-build

      - name: Unpack build files
        run: |
          tar -zxf build.tgz

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./docker/Dockerfile
          push: false
          load: true
          tags: hdk-build.${{ inputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      
        # https://github.com/docker/build-push-action/issues/252
      -  name: Move cache
         run: |
            mv /tmp/.buildx-cache /tmp/.buildx-cache-old
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Start the container
        run:  |
          docker run -id --name hdk-build.${{ inputs.name }} --network host hdk-build.${{ inputs.name }}:latest
          docker cp build.tgz hdk-build.${{ inputs.name }}:/_work

      - name: Test
        run: docker exec -u ghrunner hdk-build.${{ inputs.name }} bash /_work/scripts/conda/test.sh

